spring:
  application:
    name: furniture
  datasource:
    url: jdbc:mysql://localhost:3306/furniture
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  devtools:
    restart:
      enabled: true
logging:
  level:
    org.springframework.web: DEBUG
  file:
    name: app.log
