
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/furniture2
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
  mail:
    host: smtp.gmail.com
    port: 587
    username: tthanhbinh30041975@gmail.com
    password: Thanhbinh30041975
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          starttls.required: true
jwt:
  secret-key: "SjUvcKQ2lQDUTWbWFAvzUgkezufZY5tHjj1lDs8eXdP24vesaKnsZXxcXpHQktwjq8DBoirBhBr5GXr5vsbXLA"
springdoc:
  api-docs:
    path: /api-docs
server:
  port: 8084