spring:
  application:
    name: furniture
  profiles:
    active: dev
#  datasource:
#    url: jdbc:mysql://localhost:3306/furniture
#    username:
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  devtools:
    restart:
      enabled: true
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username:
#    password:
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

#create jwt-secret-key:
#1. python3:
#import secrets
#print(secrets.token_urlsafe(64))
#2 bash:
# openssl rand -base64 64
#jwt:
#  secret-key: