spring:
  application:
    name: furniture
  datasource:
    url: jdbc:mysql://localhost:3306/furniture
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  devtools:
    restart:
      enabled: true
logging:
  level:
    org.springframework.web: DEBUG
  file:
    name: app.log
#create jwt-secret-key:
#1. python3:
#import secrets
#print(secrets.token_urlsafe(64))
#2 bash:
# openssl rand -base64 64
jwt:
  secret-key: "SjUvcKQ2lQDUTWbWFAvzUgkezufZY5tHjj1lD-8eXdP24vesaKn-ZXxcXpHQktwjq8DBoirBhBr5GXr5vsbXLA"