spring:
  datasource:
    url: jdbc:mysql://localhost:3306/furniture
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: true
          starttls.required: true
          ssl.trust: smtp.gmail.com
jwt:
  secret-key: "SjUvcKQ2lQDUTWbWFAvzUgkezufZY5tHjj1lDs8eXdP24vesaKnsZXxcXpHQktwjq8DBoirBhBr5GXr5vsbXLA"
